// import Routes from 'next-routes';
const routes = require('next-routes');

/**
 * routes.add([name], pattern = /name, page = name)
   routes.add(object)
 */

export default routes()
  .add('dashboard', '/', '/trending')
  .add('login', '/login', '/')
  .add('contact', '/contact', '/contact')
  .add('video', '/video/:id', '/video')
  .add('store', '/store/:id', '/store')
  .add('gallery', '/gallery/:id', '/gallery')
  .add('page', '/page/:id', '/page')
  .add('feed', '/post/:id', '/post')
  .add('message', '/messages', '/messages')
  .add('notifications', '/notifications', '/notifications')
  .add('notification-setting', '/notification-setting', '/notification-setting')
  .add('help', '/help', '/help')
  // .add('topic', '/help/:slug', '/help/topic')
  // .add('help-detail', '/help/:slugCategory/:slugTitle', '/help/detail')
  .add('mobile-help-detail', '/mobile-help/:slugCategory/:slugTitle', '/help/mobile-detail')
  .add('cart', '/cart', '/cart')
  .add('error', '/error', '/error')
  .add('home', '/home', '/home')
  .add('search', '/search', '/search')
  .add('discover', '/discover', '/discover')
  .add('hashtag', '/hashtag', '/hashtag')
  .add('trending', '/trending', '/trending')
  .add('following-post', '/following-post', '/following-post')
  .add('model-list-follow', '/model/list-follow/:id', '/model/list-follow')
  .add('my-follow', '/my-follow', '/my-follow')
  .add('most-view', '/most-view', '/most-view')
  .add('ruby-package-payload', '/ruby-package', '/ruby-package')
  .add('payment-success', '/payment/success', '/payment/success')
  .add('payment-cancel', '/payment/cancel', '/payment/cancel')
  .add('live-now', '/live-now', '/live-now')
  .add('model-media-profile', '/hashtag/media-profile', '/model/media-profile')
  .add('top-caster', '/top-caster', '/model')
  .add('recast', '/recast', '/recast')
  .add('diamond-to-ruby', '/diamond-to-ruby', '/diamond-to-ruby')

  // performer
  .add('models', '/model', '/model')
  .add('banking', '/model/banking', '/model/banking')
  .add('bookmarks', '/model/bookmarks', '/model/bookmarks')
  .add('block-countries', '/model/block-countries', '/model/block-countries')
  .add('block-user', '/model/block-user', '/model/block-user')
  .add('account', '/model/account', '/model/account')
  .add('earning', '/model/earning', '/model/earning')
  .add('feed-manager', '/model/my-post', '/model/my-post')
  .add('gallery-manager', '/model/my-gallery', '/model/my-gallery')
  .add('order-manager', '/model/my-order', '/model/my-order')
  .add('store-manager', '/model/my-store', '/model/my-store')
  .add('video-manager', '/model/my-video', '/model/my-video')
  .add('my-subscriber', '/model/my-subscriber', '/model/my-subscriber')
  .add('story-manager', '/model/my-story', '/model/my-story')
  .add('payout-request', '/model/payout-request', '/model/payout-request')
  .add('live', '/live', '/model/live')
  .add('private-waiting-room', '/model/private-waiting-room', '/model/private-waiting-room')
  .add('broadcard-analytics', '/model/broadcard-analytics', '/model/broadcard-analytics')
  .add('not-qualified', '/model/not-qualified', '/model/not-qualified')
  .add('user-private-watting-room', '/private-waiting-room/:username', 'user/private-waiting-room')
  .add('user-private-accept-room', '/private-accept-room/:username', 'user/private-accept-room')
  .add('model-waiting-room', '/go-live', '/go-live')
  .add('wallet', '/wallet', '/wallet')
  .add('public-stream', '/stream/:username', '/stream')
  .add('user-private-chat', '/stream/privatechat/:username', '/stream/privatechat')
  .add('model-private-chat', '/model/privatechat', '/model/live/privatechat')
  .add('webrtc-user-private-chat', '/stream/webrtc/privatechat/:username', '/stream/webrtc/privatechat')
  .add('broadcaster-dashboard', '/broadcaster-dashboard', '/broadcaster-dashboard')
  .add('cross-promotion', '/cross-promotion', '/cross-promotion')
  .add('cross-promotion-success', '/cross-promotion/success', '/cross-promotion/success')
  .add('following-fans', '/following-fans','/following-fans')
  // must be in the last
  .add('related', '/related', 'model/related')
  .add('model', '/:username', '/model/profile');
